"""Import and convert detection rules from the Sage project into Vinci ADR format.

Reads threat YAML rules from the Sage repository (Tache 1/sage-repo/threats/*.yaml),
validates rule IDs and regex patterns, transforms the schema to Vinci ADR ThreatRule
definitions, and outputs them into rules/sage/*.yaml.

Attribution:
- Original author: Gen Digital Inc.
- License: Detection Rule License (DRL) 1.1
"""

import argparse
import re
import shutil
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import yaml

# Regex pattern for rule ID validation (supports 1 to 3 alpha segments up to 10 chars)
RULE_ID_PATTERN = re.compile(r"^[A-Z]{2,6}(-[A-Z]{2,10}){1,3}-\d{3,4}$")

# Severity mapping: Sage -> Vinci ADR
SEVERITY_MAP = {
    "critical": "critical",
    "warning": "medium",
    "info": "low",
}

# Action mapping: Sage -> Vinci ADR
ACTION_MAP = {
    "critical": "block",
    "warning": "ask",
    "info": "allow",
}

HEADER_COMMENT = (
    "# Rules imported from the Sage project (threats/).\n"
    "# Original author: Gen Digital Inc. — License: DRL-1.1\n"
    "# Auto-generated by scripts/import_sage_rules.py — DO NOT EDIT BY HAND.\n\n"
)


def parse_args() -> argparse.Namespace:
    """Parses command line arguments."""
    default_source = Path(__file__).resolve().parents[3] / "Tache 1" / "sage-repo" / "threats"
    default_output = Path(__file__).resolve().parents[1] / "rules" / "sage"

    parser = argparse.ArgumentParser(
        description="Import and convert Sage threat detection rules to Vinci ADR format."
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=default_source,
        help=f"Path to Sage threats directory (default: {default_source})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=default_output,
        help=f"Path to Vinci ADR output rules directory (default: {default_output})",
    )
    return parser.parse_args()


def import_sage_rules(
    source_dir: Path, output_dir: Path
) -> tuple[int, int, list[tuple[str, str]], dict[str, int]]:
    """Converts Sage YAML rules to Vinci ADR rule files.

    Args:
        source_dir: Source directory containing Sage threat YAML files.
        output_dir: Output directory to write converted Vinci ADR rules.

    Returns:
        Tuple of (total_read, excluded_count, skipped_regex, severity_counts).

    Raises:
        ValueError: If a rule ID does not conform to the expected format.
        FileNotFoundError: If the source directory does not exist.
    """
    if not source_dir.exists() or not source_dir.is_dir():
        raise FileNotFoundError(f"Sage threats source directory not found: {source_dir}")

    # Idempotent output directory setup: remove existing YAML files in output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    for existing_file in output_dir.glob("*.yaml"):
        try:
            existing_file.unlink()
        except OSError:
            pass

    total_read = 0
    excluded_count = 0
    skipped_regex: list[tuple[str, str]] = []
    severity_counts: Counter[str] = Counter()

    source_files = sorted(source_dir.glob("*.yaml"))

    for source_file in source_files:
        if source_file.name == "dummy.yaml":
            # Count dummy testing rules as excluded
            try:
                with open(source_file, "r", encoding="utf-8") as f:
                    dummy_data = yaml.safe_load(f)
                    if isinstance(dummy_data, list):
                        total_read += len(dummy_data)
                        excluded_count += len(dummy_data)
            except (yaml.YAMLError, OSError):
                pass
            continue

        try:
            with open(source_file, "r", encoding="utf-8") as f:
                rules_data = yaml.safe_load(f)
        except (yaml.YAMLError, OSError) as e:
            print(f"[WARNING] Could not read {source_file.name}: {e}", file=sys.stderr)
            continue

        if not isinstance(rules_data, list):
            continue

        converted_file_rules: list[dict[str, Any]] = []

        for item in rules_data:
            if not isinstance(item, dict):
                continue

            total_read += 1
            category = str(item.get("category", "")).strip()

            if category == "testing":
                excluded_count += 1
                continue

            rule_id = str(item.get("id", "")).strip()
            if not RULE_ID_PATTERN.match(rule_id):
                raise ValueError(
                    f"Invalid rule ID '{rule_id}' in {source_file.name}. Does not match expected pattern."
                )

            pattern = item.get("pattern", "")
            if not isinstance(pattern, str) or not pattern:
                skipped_regex.append((rule_id, "Empty or non-string pattern"))
                continue

            # Verify pattern compilation
            try:
                re.compile(pattern, re.IGNORECASE | re.MULTILINE)
            except re.error as err:
                skipped_regex.append((rule_id, str(err)))
                continue

            title = str(item.get("title", rule_id)).strip()
            name = title[:120]
            description = f"{title} [source: Sage {rule_id}]"

            raw_severity = str(item.get("severity", "warning")).lower().strip()
            severity = SEVERITY_MAP.get(raw_severity, "medium")
            action = ACTION_MAP.get(raw_severity, "ask")

            match_on = str(item.get("match_on", "")).strip()
            confidence = item.get("confidence", 0.90)
            flags = item.get("flags", [])

            tags = [
                "sage",
                f"sage_id={rule_id}",
                f"match_on={match_on}",
                f"confidence={confidence}",
            ]
            if isinstance(flags, list):
                tags.extend(str(flg) for flg in flags if flg)
            elif isinstance(flags, str) and flags:
                tags.append(flags)

            adr_rule = {
                "id": rule_id,
                "name": name,
                "description": description,
                "category": category,
                "patterns": [pattern],
                "severity": severity,
                "action": action,
                "enabled": True,
                "mitre_atlas_id": None,
                "tags": tags,
            }

            converted_file_rules.append(adr_rule)
            severity_counts[severity] += 1

        if converted_file_rules:
            out_file = output_dir / source_file.name
            with open(out_file, "w", encoding="utf-8") as f:
                f.write(HEADER_COMMENT)
                yaml.dump(
                    converted_file_rules,
                    f,
                    sort_keys=False,
                    allow_unicode=True,
                    default_flow_style=False,
                )

    # Copy LICENSE if available
    license_src = source_dir / "LICENSE"
    if not license_src.exists():
        license_src = source_dir.parent / "LICENSE"

    if license_src.exists():
        try:
            shutil.copy2(license_src, output_dir / "LICENSE")
        except OSError:
            pass

    return total_read, excluded_count, skipped_regex, dict(severity_counts)


def main() -> None:
    """Main execution function."""
    args = parse_args()

    print("=" * 80)
    print(" Vinci ADR: Sage Rules Import & Conversion ")
    print("=" * 80)
    print(f"Source : {args.source}")
    print(f"Output : {args.output}\n")

    try:
        total_read, excluded_count, skipped_regex, severity_counts = import_sage_rules(
            args.source, args.output
        )
    except (ValueError, FileNotFoundError, OSError) as e:
        print(f"\n[ERROR] Failed to import Sage rules: {e}", file=sys.stderr)
        sys.exit(1)

    total_written = sum(severity_counts.values())

    print("Conversion Summary:")
    print(f"  • Total rules read     : {total_read}")
    print(f"  • Excluded (dummy/test): {excluded_count}")
    print(f"  • Skipped (regex error): {len(skipped_regex)}")
    if skipped_regex:
        for r_id, reason in skipped_regex:
            print(f"      - {r_id}: {reason}")
    print(f"  • Total rules written  : {total_written}")
    print(f"      - Critical (block) : {severity_counts.get('critical', 0)}")
    print(f"      - Medium (ask)     : {severity_counts.get('medium', 0)}")
    print(f"      - Low (allow)      : {severity_counts.get('low', 0)}")
    print("=" * 80)

    if total_written > 0:
        print(
            f"\n[SUCCESS] Successfully converted and wrote {total_written} rules to {args.output}\n"
        )
        sys.exit(0)
    else:
        print("\n[FAILURE] No rules were written.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
