"""LLM Provider abstraction and implementations for Tier 2 Deep reasoning.

Provides an interchangeable interface (LLMProvider) decoupling cognitive reasoning
logic from specific LLM engines. Includes a deterministic MockLLMProvider for offline
testing and a lightweight GeminiProvider using stdlib urllib without external SDK dependencies.
"""

import json
import os
import urllib.error
import urllib.request
from abc import ABC, abstractmethod
from typing import Any

import structlog

logger = structlog.get_logger()


class LLMProviderError(RuntimeError):
    """Raised when an LLM provider fails to produce a response."""


class LLMProvider(ABC):
    """Abstract base class for Tier 2 cognitive LLM providers."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable name of the LLM provider."""

    @property
    @abstractmethod
    def is_available(self) -> bool:
        """Whether the provider is configured and available for inference."""

    @abstractmethod
    def generate(
        self,
        prompt: str,
        *,
        system: str | None = None,
        temperature: float = 0.0,
        max_tokens: int = 1024,
        json_mode: bool = False,
    ) -> str:
        """Generates text from the language model.

        Args:
            prompt: User prompt content.
            system: Optional system instruction prompt.
            temperature: Sampling temperature (0.0 for deterministic output).
            max_tokens: Maximum tokens to generate.
            json_mode: If True, instructs the model to produce valid JSON output.

        Returns:
            Raw string text generated by the model.

        Raises:
            LLMProviderError: If the provider fails to generate text.
        """


class MockLLMProvider(LLMProvider):
    """Deterministic mock LLM provider for unit tests and offline development.

    Attributes:
        calls: Log of all calls made to generate(), storing parameters.
    """

    def __init__(
        self,
        responses: list[str] | None = None,
        default_response: str | None = None,
    ) -> None:
        """Initializes the mock provider.

        Args:
            responses: Ordered queue of responses returned one-by-one per generate() call.
            default_response: Fallback response returned once queue is empty.
        """
        self._responses: list[str] = list(responses) if responses is not None else []
        self._default_response: str = (
            default_response
            if default_response is not None
            else (
                '{"is_malicious": false, "severity": "low", "recommended_decision": "allow", '
                '"confidence": 0.9, "rationale": "Forensic analysis: legitimate network diagnostic inquiry", '
                '"indicators": []}'
            )
        )
        self.calls: list[dict[str, Any]] = []

    @property
    def name(self) -> str:
        """Returns the mock provider identifier."""
        return "mock"

    @property
    def is_available(self) -> bool:
        """Mock provider is always available."""
        return True

    def generate(
        self,
        prompt: str,
        *,
        system: str | None = None,
        temperature: float = 0.0,
        max_tokens: int = 1024,
        json_mode: bool = False,
    ) -> str:
        """Records call metadata and returns queued or default response.

        Args:
            prompt: User prompt content.
            system: Optional system prompt.
            temperature: Sampling temperature.
            max_tokens: Max output tokens.
            json_mode: Whether JSON output was requested.

        Returns:
            Mocked string response.
        """
        self.calls.append(
            {
                "prompt": prompt,
                "system": system,
                "temperature": temperature,
                "max_tokens": max_tokens,
                "json_mode": json_mode,
            }
        )

        if self._responses:
            return self._responses.pop(0)

        return self._default_response


class GeminiProvider(LLMProvider):
    """Google Gemini API provider using Python standard library urllib.

    Attributes:
        model: Target Gemini model identifier (e.g. "gemini-2.5-flash").
        timeout: Request timeout in seconds.
        auth_mode: Explicit authentication mode ("api_key" or "bearer").
    """

    def __init__(
        self,
        api_key: str | None = None,
        model: str = "gemini-3.6-flash",
        timeout: float = 60.0,
        auth_mode: str | None = None,
        thinking_level: str | None = "low",
    ) -> None:
        """Initializes the Gemini provider without performing network calls.

        Args:
            api_key: Gemini API key or OAuth bearer token. If None, reads GEMINI_API_KEY from environment.
            model: Target Gemini model name.
            timeout: HTTP request timeout in seconds.
            auth_mode: Optional explicit auth mode ("api_key" or "bearer"). If None, auto-detected.
            thinking_level: Gemini 3 reasoning depth ("low"/"high"). "low" keeps latency ~2s for
                structured classification tasks. Set to None to omit (e.g. non-Gemini-3 models).
        """
        self._api_key = api_key if api_key is not None else os.environ.get("GEMINI_API_KEY")
        self.model = model
        self.timeout = timeout
        self.auth_mode = auth_mode
        self.thinking_level = thinking_level

    @property
    def _resolved_auth_mode(self) -> str:
        """Resolves authentication mode ('api_key' or 'bearer')."""
        if self.auth_mode in ("api_key", "bearer"):
            return self.auth_mode
        if self._api_key and (self._api_key.startswith("AIza") or self._api_key.startswith("AQ.")):
            return "api_key"
        return "bearer"

    @property
    def is_available(self) -> bool:
        """Checks if a non-empty API key is configured."""
        return bool(self._api_key and self._api_key.strip())

    @property
    def name(self) -> str:
        """Returns the provider identifier."""
        return f"gemini:{self.model}"

    def generate(
        self,
        prompt: str,
        *,
        system: str | None = None,
        temperature: float = 0.0,
        max_tokens: int = 1024,
        json_mode: bool = False,
    ) -> str:
        """Sends a generateContent request to the Gemini API.

        Args:
            prompt: User prompt text.
            system: Optional system instruction text.
            temperature: Sampling temperature.
            max_tokens: Maximum response tokens.
            json_mode: If True, sets response MIME type to application/json.

        Returns:
            Generated text content from the first candidate part.

        Raises:
            LLMProviderError: If the API key is missing or request/parsing fails.
        """
        if not self.is_available:
            raise LLMProviderError("GEMINI_API_KEY is missing or empty")

        payload: dict[str, Any] = {
            "contents": [{"role": "user", "parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": temperature,
                "maxOutputTokens": max_tokens,
            },
        }

        if system:
            payload["systemInstruction"] = {"parts": [{"text": system}]}

        if json_mode:
            payload["generationConfig"]["responseMimeType"] = "application/json"

        # Gemini 3 thinking models default to deep reasoning (~40s, highly variable).
        # For structured classification, "low" keeps latency ~2s and reliable.
        if self.thinking_level is not None:
            payload["generationConfig"]["thinkingConfig"] = {"thinkingLevel": self.thinking_level}

        base_url = (
            f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent"
        )
        headers: dict[str, str] = {"Content-Type": "application/json"}

        if self._resolved_auth_mode == "api_key":
            url = f"{base_url}?key={self._api_key}"
        else:
            url = base_url
            headers["Authorization"] = f"Bearer {self._api_key}"

        req_data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(url, data=req_data, headers=headers, method="POST")

        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                resp_bytes = resp.read()
                data = json.loads(resp_bytes.decode("utf-8"))
                return data["candidates"][0]["content"]["parts"][0]["text"]
        except urllib.error.HTTPError as e:
            status = e.code
            try:
                err_body = e.read().decode("utf-8", errors="replace")
            except (OSError, UnicodeDecodeError):
                err_body = ""
            logger.error("Gemini API HTTP error", status_code=status, error=err_body[:200])
            raise LLMProviderError(f"Gemini API returned HTTP {status}: {err_body[:200]}") from e
        except urllib.error.URLError as e:
            logger.error("Gemini API network error", reason=str(e.reason))
            raise LLMProviderError(f"Gemini API network connection failed: {e.reason}") from e
        except TimeoutError as e:
            logger.error("Gemini API request timed out", timeout=self.timeout)
            raise LLMProviderError(f"Gemini API request timed out after {self.timeout}s") from e
        except (json.JSONDecodeError, KeyError, IndexError) as e:
            logger.error("Failed to parse Gemini API response", error=str(e))
            raise LLMProviderError(f"Invalid response payload from Gemini API: {e}") from e
