"""Output Guard Engine for validating and sanitizing AI generated responses."""

from __future__ import annotations

import re
import time

import structlog

from vinci_adr.output_guard.schema import (
    OutputDecision,
    OutputGuardConfig,
    OutputSafetyVerdict,
    SafetyCategory,
)
from vinci_adr.tier1_fast.heuristics import HeuristicsEngine
from vinci_adr.tier1_fast.secrets_scanner import SecretsScanner

logger = structlog.get_logger()

# Chemical, Biological, Radiological, and Nuclear (CBRN) threat indicators (S6)
# Patterns support both English and French variants for international coverage.
CBRN_PATTERNS = [
    re.compile(
        r"(?i)\b(?:sarin|tabun|soman|vx\s+nerve\s+agent|novichok)\b.*(?:synthes|synthétis|precursor|précurseur|recipe|recette|formula|formule|weaponiz|armé|arme)"
    ),
    re.compile(
        r"(?i)\b(?:anthrax|ricin|botulinum|ebola|smallpox|variole)\b.*(?:cultivat|cultur|aerosol|aérosol|weaponiz|armé|purif|extract)"
    ),
    re.compile(
        r"(?i)\b(?:dirty\s+bomb|bombe\s+sale|radiological\s+dispersal|dispersion\s+radiologique|enriched\s+uranium|uranium\s+enrichi|weapon-grade\s+plutonium|plutonium\s+militaire)\b.*(?:assembl|assembler|detonat|déton|construct|fabriqu)"
    ),
]

# Offensive Cyberattack generation indicators (S8)
OFFENSIVE_CYBER_PATTERNS = [
    re.compile(r"(?i)(?:bash\s+-i\s+>&|\/dev\/tcp\/\d+\.\d+\.\d+\.\d+\/\d+|\/dev\/udp\/)"),
    re.compile(r"(?i)(?:nc(?:cat)?\s+-[a-z]*e\s+\/(?:bin|usr)\/(?:ba)?sh)"),
    re.compile(r"(?i)(?:Invoke-Mimikatz|sekurlsa::logonpasswords|lsadump::sam|privilege::debug)"),
    re.compile(r"(?i)(?:msfvenom\s+-p\s+windows\/meterpreter|msfvenom\s+-p\s+linux\/)"),
    re.compile(r"(?i)(?:powershell(?:\.exe)?\s+-(?:nop|enc|encodedcommand)\s+[A-Za-z0-9+/=]{40,})"),
]


class OutputGuardEngine:
    """Evaluates and sanitizes AI generated outputs against MLCommons risks and DLP policies.

    Enforces:
    - Data Loss Prevention (DLP): Detection and redaction of credentials, API keys, tokens.
    - Cyberattack Generation Prevention: Blocking of reverse shells, mimikatz dumps, weaponized exploits.
    - MLCommons Safety Taxonomy compliance (CBRN, hate speech, dangerous goods).

    Usage:
        guard = OutputGuardEngine()
        verdict = guard.scan_output(ai_response_text)
        if verdict.decision == OutputDecision.ALLOW:
            deliver(ai_response_text)
        elif verdict.decision == OutputDecision.REDACT:
            deliver(verdict.sanitized_text)
        else:
            block_response(verdict.reason)
    """

    def __init__(
        self,
        config: OutputGuardConfig | None = None,
        secrets_scanner: SecretsScanner | None = None,
        heuristics_engine: HeuristicsEngine | None = None,
    ) -> None:
        """Initialize the Output Guard Engine.

        Args:
            config: Configuration settings for the output guard.
            secrets_scanner: Optional pre-configured SecretsScanner instance.
            heuristics_engine: Optional pre-configured HeuristicsEngine instance.
        """
        self.config = config or OutputGuardConfig()
        self._secrets_scanner = secrets_scanner or SecretsScanner()
        self._heuristics_engine = heuristics_engine or HeuristicsEngine()
        logger.info(
            "OutputGuardEngine initialized",
            strict_mode=self.config.strict_mode,
            enable_dlp=self.config.enable_dlp,
            enable_cyber_check=self.config.enable_cyber_check,
        )

    def redact_secrets(self, text: str) -> tuple[str, list[str]]:
        """Redact all sensitive secrets found in output text.

        Args:
            text: Raw AI response text containing potential secrets.

        Returns:
            Tuple of (sanitized_text, list_of_detected_secret_types).
        """
        if not text:
            return text, []

        matches = self._secrets_scanner.scan(text)
        if not matches:
            return text, []

        sanitized = text
        detected_types: list[str] = []

        # Sort matches by length descending to replace longest specific tokens first
        for m in sorted(matches, key=lambda x: len(x.full_match), reverse=True):
            secret_type = m.secret_type
            if secret_type not in detected_types:
                detected_types.append(secret_type)

            replacement = f"[REDACTED_SECRET: {secret_type}]"
            # Replace exact matched token
            if m.full_match in sanitized:
                sanitized = sanitized.replace(m.full_match, replacement)

        return sanitized, detected_types

    def scan_output(self, text: str) -> OutputSafetyVerdict:
        """Evaluate an AI generated output and return a comprehensive safety verdict.

        Args:
            text: The text output generated by the AI model.

        Returns:
            OutputSafetyVerdict containing decision, flagged categories, and sanitized text.
        """
        start_time = time.perf_counter()

        # Handle empty/whitespace output gracefully
        if not text or not text.strip():
            latency = (time.perf_counter() - start_time) * 1000.0
            return OutputSafetyVerdict(
                is_safe=True,
                decision=OutputDecision.ALLOW,
                flagged_categories=[],
                sanitized_text=text,
                reason="Empty output is safe",
                latency_ms=round(latency, 2),
            )

        flagged_categories: list[SafetyCategory] = []
        detected_secrets: list[str] = []
        decision = OutputDecision.ALLOW
        reason = "Output is safe"
        sanitized_text: str | None = None

        # -------------------------------------------------------------
        # STEP 1: CBRN & Critical Safety Check (S6)
        # -------------------------------------------------------------
        if self.config.enable_mlcommons_check:
            for pattern in CBRN_PATTERNS:
                if pattern.search(text):
                    flagged_categories.append(SafetyCategory.S6_CBRN_WEAPONS)
                    decision = OutputDecision.BLOCK
                    reason = "Critical policy violation: Dangerous CBRN synthesis/weaponization instructions detected"
                    latency = (time.perf_counter() - start_time) * 1000.0
                    return OutputSafetyVerdict(
                        is_safe=False,
                        decision=decision,
                        flagged_categories=flagged_categories,
                        sanitized_text=None,
                        confidence=1.0,
                        detected_secrets=[],
                        reason=reason,
                        latency_ms=round(latency, 2),
                    )

        # -------------------------------------------------------------
        # STEP 2: Offensive Cyber & Exploit Code Check (S8)
        # -------------------------------------------------------------
        if self.config.enable_cyber_check:
            for pattern in OFFENSIVE_CYBER_PATTERNS:
                if pattern.search(text):
                    flagged_categories.append(SafetyCategory.S8_CYBERATTACKS)
                    decision = OutputDecision.BLOCK
                    reason = "Critical policy violation: Generated offensive payload or reverse shell detected"
                    latency = (time.perf_counter() - start_time) * 1000.0
                    return OutputSafetyVerdict(
                        is_safe=False,
                        decision=decision,
                        flagged_categories=flagged_categories,
                        sanitized_text=None,
                        confidence=1.0,
                        detected_secrets=[],
                        reason=reason,
                        latency_ms=round(latency, 2),
                    )

        # -------------------------------------------------------------
        # STEP 3: Data Loss Prevention (DLP) Secrets Check (S10)
        # -------------------------------------------------------------
        if self.config.enable_dlp:
            cleaned_text, secrets = self.redact_secrets(text)
            if secrets:
                flagged_categories.append(SafetyCategory.S10_SECRETS_CREDENTIALS)
                detected_secrets = secrets

                if self.config.strict_mode:
                    decision = OutputDecision.BLOCK
                    reason = (
                        f"Strict mode: Output blocked due to secret leak ({', '.join(secrets)})"
                    )
                    sanitized_text = None
                else:
                    decision = OutputDecision.REDACT
                    sanitized_text = cleaned_text
                    reason = (
                        f"DLP: Sanitized {len(secrets)} leaked secret(s) ({', '.join(secrets)})"
                    )

        latency = (time.perf_counter() - start_time) * 1000.0
        is_safe = decision != OutputDecision.BLOCK

        return OutputSafetyVerdict(
            is_safe=is_safe,
            decision=decision,
            flagged_categories=flagged_categories,
            sanitized_text=sanitized_text if decision == OutputDecision.REDACT else text,
            confidence=1.0,
            detected_secrets=detected_secrets,
            reason=reason,
            latency_ms=round(latency, 2),
        )
